### ISSUE TITLE
Wrong PDU sms text

### ISSUE THREAD

**Issue by 3sco** [jackkum/PHPPDU#18]
Is this project work's corectly? First of all needed to include all the files maunally autoloader didnt works corectly. Second thing is that sms is incorect. You can try to check on page:
http://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/

Exampel

jackkum/PHPPDU: 0B911356131313F321000A91602143658700000CC8F71D14969741F977FD07 
corect: 07911356131313F311000A9260214365870000AA0CC8F71D14969741F977FD07

Code below:
$pdu = new \jackkum\PHPPDU\Submit();

$pdu->setSca('+31653131313');
$pdu->setAddress("0612345678");
$pdu->setPid(0);
$pdu->setDcs(0);
$pdu->setData("How are you?");

Please verify what is wrong. How to set :
Validity-Period on 4 days?

**Comment by 3sco** [comment]
Problem is with $pdu->setSca('+31653131313'); how should be set Service Centre address ?

**Comment by jackkum** [comment]
Here is successful PHPUnit tests (https://github.com/jackkum/PHPPDU/blob/master/tests/pduTest.php) Here (https://travis-ci.org/jackkum/PHPPDU), all tests is passed.
Unfortunately I'm writing test for the Russian phone numbers, tomorrow i can look and fix this :smile:

**Comment by 3sco** [comment]
Try set Sca and then check it

**Comment by jackkum** [comment]
About validity period, have a two way:
```php
$pdu->setVp('2015-06-19 00:00:00');
```
or 
```php
$pdu->setVp(3600 * 24 * 4);
```
https://github.com/jackkum/PHPPDU/blob/master/PDU/VP.php#L121 - here is a logic formating

**Comment by 3sco** [comment]
Great thx. I will test with setSca tomorrow.

**Comment by jackkum** [comment]
```php
$pdu = new Submit();

$pdu->setSca('+31653131313');
$pdu->setAddress("+48660548430");
//$pdu->setPid();
//$pdu->setDcs();
$pdu->setData("łóśćąę");

foreach($pdu->getParts() as $part){
	echo get_class($part), PHP_EOL;
	echo (string) $part, PHP_EOL;
}
```

result: 07911356131313F321000B918466508434F0000806014200F3015B010701050119

**Comment by 3sco** [comment]
did you change somting

**Comment by jackkum** [comment]
created this file: https://github.com/jackkum/PHPPDU/blob/master/PDU/PID.php
and change encode methods: https://github.com/jackkum/PHPPDU/blob/master/PDU/Helper.php#L30

**Comment by 3sco** [comment]
All changes are in 1.2.2 version?

**Comment by jackkum** [comment]
Yes, i make clear install, and i have this changes.

**Comment by 3sco** [comment]
I test send sms 
0031000B918466508434F00008AA060105011900F30142015B0107
did get this sms

pdu = \jackkum\PHPPDU\Submit();
$pdu->setVp(3600 * 24 * 4);
$pdu->setData("łóśćąę");


correct recived : 
0011000B918466508434F00008AA0C0105011900F30142015B0107

**Comment by jackkum** [comment]
Now works correctly?

**Comment by 3sco** [comment]
yes
