### ISSUE TITLE
Autoload

### ISSUE THREAD

**Issue by 3sco** [jackkum/PHPPDU#19]
Hi.

There is some problems with autoload : 
require_once '../vendor/autoload.php';
$pdu = new \jackkum\PHPPDU\Submit();

Get Fatal error: Class 'jackkum\PHPPDU\Submit' not found 

I need to include all class manualy.

require_once '../vendor/autoload.php';
require_once '../vendor/jackkum/phppdu/vendor/autoload.php';
require_once '../vendor/jackkum/phppdu/PDU/Type.php';
require_once '../vendor/jackkum/phppdu/PDU/DCS.php';
require_once '../vendor/jackkum/phppdu/PDU/SCTS.php';
require_once '../vendor/jackkum/phppdu/PDU/Data.php';
require_once '../vendor/jackkum/phppdu/PDU/Helper.php';
require_once '../vendor/jackkum/phppdu/PDU/Data/Part.php';
require_once '../vendor/jackkum/phppdu/PDU/Data/Header.php';
require_once '../vendor/jackkum/phppdu/PDU/SCA.php';
require_once '../vendor/jackkum/phppdu/PDU/SCA/Type.php';
require_once '../vendor/jackkum/phppdu/PDU/Type/Submit.php';
require_once '../vendor/jackkum/phppdu/PDU/Type/Deliver.php';
require_once '../vendor/jackkum/phppdu/PDU/Type/Report.php';
require_once '../vendor/jackkum/phppdu/PDU.php';
require_once '../vendor/jackkum/phppdu/Deliver.php';
require_once '../vendor/jackkum/phppdu/Submit.php';
require_once '../vendor/jackkum/phppdu/PDU/VP.php';

I use many packages and didnt have problems with others.

**Comment by jackkum** [comment]
try this, without first backslash
```php
$pdu = new jackkum\PHPPDU\Submit();
```
In others packages using with first backslash?

**Comment by 3sco** [comment]
Didnt works
Fatal error: Class 'jackkum\PHPPDU\Submit

**Comment by 3sco** [comment]
one more thing how to send 16bit ?

**Comment by jackkum** [comment]
```php
$dcs = new PDU\DCS();
$dcs->setTextAlphabet(PDU\DCS::ALPHABET_UCS2);
$pdu->setDcs($dcs);
$pdu->setData('How are you?');
```
now i'm working over sca

**Comment by 3sco** [comment]
didnt work
try
$pdu->setData("łóśćąę");
result
0031000B918466508434F000E0AA0600C500C300C500C400C400C4

http://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/
get : ÅÃÅÄÄÄ

should be : 
0001000B918466508434F000080C014200F3015B010701050119

**Comment by jackkum** [comment]
can you show your composer.json?
```
{
  "require": {
    "jackkum/phppdu": "1.2.*"
  }
}
```

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing jackkum/phppdu (v1.2.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

test.php on the same folder
```php
#!/usr/bin/php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use jackkum\PHPPDU\Submit;

$pdu = new Submit();
$pdu->setAddress("+79025449307");
$pdu->setData('Test');

echo (string) $pdu;
```

result: 0021000B919720459403F70000

**Comment by 3sco** [comment]
{
    "name": "TEST",
    "description": "TEST",
    "license": "Propitiatory",
    "keywords": [
        "TEST"
    ],
    "homepage": "http://www.test.pl",
    "require": {
        "php": ">=5.4",
        "elasticsearch/elasticsearch": "~1.3",
        "guzzlehttp/guzzle": "4.*",
        "guzzle/plugin-cookie": "3.7.*@dev",
        "smalot/pdfparser": "~0.9",
        "zendframework/zend-mail" : "~2.3",
        "dompdf/dompdf" : "0.6.*",
        "jackkum/phppdu" : "~1.2"
    }
}

**Comment by 3sco** [comment]
More importent for me right now is to send polsih chars is sms:)

**Comment by jackkum** [comment]
I fixed it. :smile: now will merge dev branch and will make release. 
Can you test it?

**Comment by 3sco** [comment]
OK i didnt composer.phar self-update and update
require_once '../vendor/autoload.php';
$pdu = new \jackkum\PHPPDU\Submit(); OR $pdu = new jackkum\PHPPDU\Submit();

Fatal error: Class 'jackkum\PHPPDU\Submit' not found

Please check why msg is not converting polish chars

**Comment by 3sco** [comment]
Sorry i get Nothing to instal or update so that's why isnt work still

**Comment by jackkum** [comment]
The same on autoloader?

**Comment by 3sco** [comment]
Yes

**Comment by jackkum** [comment]
Can you show file ./vendor/composer/autoload_psr4.php ?

**Comment by 3sco** [comment]
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'jackkum\\PHPPDU\\' => array($vendorDir . '/jackkum/phppdu/vendor/jackkum/phppdu'),
    'jackkum\\' => array($vendorDir . '/jackkum/phppdu/vendor/jackkum'),
    'Zend\\Validator\\' => array($vendorDir . '/zendframework/zend-validator/src'),
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib/src'),
    'Zend\\ServiceManager\\' => array($vendorDir . '/zendframework/zend-servicemanager/src'),
    'Zend\\Mime\\' => array($vendorDir . '/zendframework/zend-mime/src'),
    'Zend\\Math\\' => array($vendorDir . '/zendframework/zend-math/src'),
    'Zend\\Mail\\' => array($vendorDir . '/zendframework/zend-mail/src'),
    'Zend\\Loader\\' => array($vendorDir . '/zendframework/zend-loader/src'),
    'Zend\\Crypt\\' => array($vendorDir . '/zendframework/zend-crypt/src'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'GuzzleHttp\\Stream\\' => array($vendorDir . '/guzzlehttp/streams/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Elasticsearch\\' => array($vendorDir . '/elasticsearch/elasticsearch/src/Elasticsearch'),
);

**Comment by 3sco** [comment]
Please check cause I cannot still send sms with polish chars. Get error with message length exceed

**Comment by 3sco** [comment]
Did you check what is going on with autoloader?

**Comment by jackkum** [comment]
Can you test it please? I'm going to sleep :sleeping:

**Comment by 3sco** [comment]
I can test it tomorrow and i let you know

**Comment by 3sco** [comment]
still the same
require_once '../vendor/autoload.php';
$pdu = new \jackkum\PHPPDU\Submit();

Fatal error: Class 'jackkum\PHPPDU\Submit' not found

**Comment by jackkum** [comment]
```json
{
  "name": "TEST",
  "description": "TEST",
  "license": "Propitiatory",
  "keywords": [
    "TEST"
  ],
  "homepage": "http://www.test.pl",
  "require": {
    "php": ">=5.4",
    "elasticsearch/elasticsearch": "~1.3",
    "guzzlehttp/guzzle": "4.",
    "guzzle/plugin-cookie": "3.7.@dev",
    "smalot/pdfparser": "~0.9",
    "zendframework/zend-mail" : "~2.3",
    "dompdf/dompdf" : "0.6.*",
    "jackkum/phppdu" : "~1.2"
  }
}
```

```bash
$ composer install -vvv
```

I installed this package on 3 other servers, and everywhere works good. 
Only one thing, i did 
```bash
$ composer self-update 
```
on one of them, and install on others
```bash
$ curl -sS https://getcomposer.org/installer | php
$ mv composer.phar /usr/local/bin/composer
```
may be you need to do self-update?

**Comment by 3sco** [comment]
I did update as always first self-update then update

**Comment by 3sco** [comment]
Its working on other computer.

**Comment by jackkum** [comment]
Can you write var_dump() to the file ./vendor/composer/ClassLoader.php?
I will write line numbers.

**Comment by 3sco** [comment]
yes i can. Im working on windows and didnt work on it but on linux is working

**Comment by jackkum** [comment]
230 - var_dump($class);
349 - var_dump($logicalPathPsr4);
350 - var_dump($this->prefixLengthsPsr4);
355 - var_dump($prefix, $length);
358 - var_dump($prefix, $length, $dir . DIRECTORY_SEPARATOR . substr($logicalPathPsr4, $length));
and launch the script

**Comment by 3sco** [comment]
string 'GuzzleHttp\ClientInterface' (length=26)
string 'GuzzleHttp/ClientInterface.php' (length=30)
array (size=5)
  'Z' => 
    array (size=8)
      'Zend\Validator\' => int 15
      'Zend\Stdlib\' => int 12
      'Zend\ServiceManager\' => int 20
      'Zend\Mime\' => int 10
      'Zend\Math\' => int 10
      'Zend\Mail\' => int 10
      'Zend\Loader\' => int 12
      'Zend\Crypt\' => int 11
  'S' => 
    array (size=1)
      'Symfony\Component\EventDispatcher\' => int 34
  'M' => 
    array (size=1)
      'Monolog\' => int 8
  'G' => 
    array (size=2)
      'GuzzleHttp\Stream\' => int 18
      'GuzzleHttp\' => int 11
  'E' => 
    array (size=1)
      'Elasticsearch\' => int 14
string 'GuzzleHttp\Stream\' (length=18)
int 18
string 'GuzzleHttp\' (length=11)
int 11
string 'GuzzleHttp\' (length=11)
int 11
string '/home/www/httpd-data/b4b05/sof3/vendor/guzzlehttp/guzzle/src/ClientInterface.php' (length=80)
string 'GuzzleHttp\Event\HasEmitterInterface' (length=36)
string 'GuzzleHttp/Event/HasEmitterInterface.php' (length=40)
array (size=5)
  'Z' => 
    array (size=8)
      'Zend\Validator\' => int 15
      'Zend\Stdlib\' => int 12
      'Zend\ServiceManager\' => int 20
      'Zend\Mime\' => int 10
      'Zend\Math\' => int 10
      'Zend\Mail\' => int 10
      'Zend\Loader\' => int 12
      'Zend\Crypt\' => int 11
  'S' => 
    array (size=1)
      'Symfony\Component\EventDispatcher\' => int 34
  'M' => 
    array (size=1)
      'Monolog\' => int 8
  'G' => 
    array (size=2)
      'GuzzleHttp\Stream\' => int 18
      'GuzzleHttp\' => int 11
  'E' => 
    array (size=1)
      'Elasticsearch\' => int 14
string 'GuzzleHttp\Stream\' (length=18)
int 18
string 'GuzzleHttp\' (length=11)
int 11
string 'GuzzleHttp\' (length=11)
int 11
string '/home/www/httpd-data/b4b05/sof3/vendor/guzzlehttp/guzzle/src/Event/HasEmitterInterface.php' (length=90)
string 'jackkum\PHPPDU\Submit' (length=21)
string 'jackkum/PHPPDU/Submit.php' (length=25)
array (size=5)
  'Z' => 
    array (size=8)
      'Zend\Validator\' => int 15
      'Zend\Stdlib\' => int 12
      'Zend\ServiceManager\' => int 20
      'Zend\Mime\' => int 10
      'Zend\Math\' => int 10
      'Zend\Mail\' => int 10
      'Zend\Loader\' => int 12
      'Zend\Crypt\' => int 11
  'S' => 
    array (size=1)
      'Symfony\Component\EventDispatcher\' => int 34
  'M' => 
    array (size=1)
      'Monolog\' => int 8
  'G' => 
    array (size=2)
      'GuzzleHttp\Stream\' => int 18
      'GuzzleHttp\' => int 11
  'E' => 
    array (size=1)
      'Elasticsearch\' => int 14

**Comment by jackkum** [comment]
Can you add more one line? 
220 - var_dump($prefix, $paths); 
i don't see my package on list. 

and can you look on the file composer.lock, there must be section 
```json
"autoload": {
  "psr-4": {
    "jackkum\\PHPPDU\\": ""
  }
}
```

**Comment by 3sco** [comment]
string 'line 220' (length=8)
string '' (length=0)
array (size=1)
  0 => string '/home/www/httpd-data/b4b05/sof3/vendor/jackkum/phppdu' (length=53)
string 'end line 220' 

it's the same
autoload": {
  "psr-4": {
    "jackkum\\PHPPDU\\": ""
  }
}

**Comment by 3sco** [comment]
sorry that was smth wrong in my project
