### ISSUE TITLE
Counting octets - TP-User-Data-Length

### ISSUE THREAD

**Issue by 3sco** [jackkum/PHPPDU#22]
For exampel : 
0031000B918466508434F00008AA010105 

010105 
01 = 0105  should be
02 = 0105
Another thing 0031 should be 0091 cause its internaltional number

file Helper.php
length should be $length += 2; not $length ++; line 188

One more thing if its sended concatenated sms you set in Data.php
const HEADER_SIZE = 8;
but should be 
const HEADER_SIZE = 7;

06080471D10201
06080471D10202

**Comment by jackkum** [comment]
0031 = 0x00 - sca not set, and 0x31 == 0b00110001 (0x11 == 0b00010001) fifth bit is set on by default for Status-Report-Request

Thanks for help, helper is changed.

**Comment by jackkum** [comment]
Yes, you are right about header size.
Why I set 8 don't remember.

**Comment by 3sco** [comment]
what about length of message in Helper.php line 188?

**Comment by jackkum** [comment]
I fixed it.
