### ISSUE TITLE
Length of one sms

### ISSUE THREAD

**Issue by 3sco** [jackkum/PHPPDU#27]
Is sms has 160 chars for exampel 
"If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to create test a" 

There should be one pdu sms but we get 2 : 

0071000B918466409439F30000AA8C06080424630201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E06

0071000B918466409439F30000AA2206080424630202E776D94D0FD3D36F3788FE068DE5E530BD0CA297E7745018 

But should be:
0011000B918466409439F30000AAA0493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B315E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E96510BD3CA783C2

**Comment by jackkum** [comment]
160 chars can be sended if text is compressed to 7 bit (default encoding for latin), unicode can be send only 70 chars.
You mean gateway may adopt 160 chars?

**Comment by 3sco** [comment]
package should recognize if its 7 bit and length of sms 
If length is more the 160 should be 2 sms and i see its not checking if msg is compresed or not

**Comment by jackkum** [comment]
Compression of text was off by default. 
And i did status report request default is off, if you want use it do code below
```php
$pdu->getType()->setSrr(1);
```

**Comment by jackkum** [comment]
Current version should be 1.2.7

**Comment by 3sco** [comment]
But it should not to be detect if msg is compresed or not?

**Comment by jackkum** [comment]
Detecting message data if there have unicode, then will be limitation is 70 chars. 
Message pass as clear text, how it can be detected on compression?

**Comment by 3sco** [comment]
Sorry you right. Why package make parts is sms is 160 chars. It should be one part.

**Comment by jackkum** [comment]
This packed was created for modem and now working with him.
May be better for the package do not split message if this don't need
I can do like this:
```php
echo (string) $pdu; // will create not splited pdu
// and this will be work
foreach($pdu->getParts() as $part){
	echo (string) $part;
}
```

**Comment by 3sco** [comment]
so it should 8bit always?  but if somebody need to send 7bit ?:)

**Comment by jackkum** [comment]
No, default will be 7bit for not unicode, if need to send 8 bit:
```php
$pdu->getDcs()->setTextCompressed(FALSE);
$pdu->setData('Hi');
```

**Comment by 3sco** [comment]
So why each message is cut for 140 chars ? if message is <= 160 should be one msg if more part each for 153 chars max

**Comment by jackkum** [comment]
Limitation is 140 bytes, for compression whe can send 160 chars in the 140 bytes

**Comment by 3sco** [comment]
"If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to create test a" how many sms should be for this text ?

**Comment by jackkum** [comment]
Only one, with my today's fixes.

**Comment by 3sco** [comment]
There is wrong length

0071000B911311113254F60000AAA006080403AE0201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD290854BEDFCB20F9BD0C92DFCB72D0BD2C07DDCBF27B1924BF9741F27B1924BF97E5A07B9ACD0685EBF4773B4C4F8FC36C 
Length is set on A0 = 160
Should be text length 98H = 152
MSG "If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS  ewwe rwe rwer wer werwe rwe rwe rwer will automatica"

0071000B911311113254F60000AA5406080403AE0202EC3C085E969BDFF236888E4ECF41F3F2B95D76D3C3F4F4DB0DA2BF416379394C2F83D06174180D22A3E764D09C6C5EB3E76433684E36AFD973B2794E06CDC9E6F59C6C06

length is 54H = 84
Should be text length 4cH = 76

**Comment by jackkum** [comment]
Just now generated:
0011000B911311113254F60000AA**97**493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29A87CBF9741F27B1924BF97E5A07B590EBA97E5F732487E2F83E4F732487E2FCB41F7349B0D0AD7E9EF76989E1E8701

```php
$pdu = new Submit();
$pdu->setVp(3600 * 24 * 4);
$pdu->setAddress("+31111123456");
$pdu->setData('If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS ewwe rwe rwer wer werwe rwe rwe rwer will automatica');
var_dump($pdu->getData());
var_dump('If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS ewwe rwe rwer wer werwe rwe rwe rwer will automatica');
echo implode("\n", array_map('trim', $pdu->getParts())),PHP_EOL;
```

result;
```bash
$ ./test.php
class jackkum\PHPPDU\PDU\Data#11 (5) {
  protected $_size =>
  int(151)
  protected $_data =>
  string(151) "If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS ewwe rwe rwer wer werwe rwe rwe rwer will automatica"
  protected $_parts =>
  array(1) {
    [0] =>
    class jackkum\PHPPDU\PDU\Data\Part#12 (5) {
      protected $_header =>
      NULL
      protected $_data =>
      string(266) "493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29A87CBF9741F27B1924BF97E5A07B590EBA97E5F732487E2F83E4F732487E2FCB41F7349B0D0AD7E9EF76989E1E8701"
      protected $_text =>
      NULL
      protected $_size =>
      int(151)
      protected $_parent =>
              ...

    }
  }
  protected $_isUnicode =>
  bool(false)
  protected $_pdu =>
  class jackkum\PHPPDU\Submit#2 (9) {
    protected $_mr =>
    int(0)
    protected $_vp =>
    class jackkum\PHPPDU\PDU\VP#9 (3) {
      protected $_datetime =>
      NULL
      protected $_interval =>
      int(345600)
      protected $_pdu =>
              ...

    }
    protected $_sca =>
    class jackkum\PHPPDU\PDU\SCA#3 (5) {
      protected $_type =>
      class jackkum\PHPPDU\PDU\SCA\Type#4 (2) {
        ...
      }
      protected $_size =>
      int(0)
      protected $_phone =>
      NULL
      protected $_encoded =>
      NULL
      protected $_isAddress =>
      bool(false)
    }
    protected $_type =>
    class jackkum\PHPPDU\PDU\Type\Submit#5 (6) {
      protected $_rp =>
      int(0)
      protected $_udhi =>
      int(0)
      protected $_srr =>
      int(0)
      protected $_vpf =>
      int(0)
      protected $_rd =>
      int(0)
      protected $_mti =>
      int(1)
    }
    protected $_address =>
    class jackkum\PHPPDU\PDU\SCA#8 (5) {
      protected $_type =>
      class jackkum\PHPPDU\PDU\SCA\Type#10 (2) {
        ...
      }
      protected $_size =>
      int(11)
      protected $_phone =>
      string(12) "+31111123456"
      protected $_encoded =>
      string(11) "31111123456"
      protected $_isAddress =>
      bool(true)
    }
    protected $_pid =>
    class jackkum\PHPPDU\PDU\PID#6 (3) {
      protected $_pid =>
      int(0)
      protected $_indicates =>
      int(0)
      protected $_type =>
      int(0)
    }
    protected $_dcs =>
    class jackkum\PHPPDU\PDU\DCS#7 (12) {
      protected $_encodeGroup =>
      int(0)
      protected $_dataEncoding =>
      int(0)
      protected $_compressedText =>
      bool(true)
      protected $_alphabet =>
      int(0)
      protected $_useMessageClass =>
      bool(false)
      protected $_classMessage =>
      int(0)
      protected $_discardMessage =>
      bool(false)
      protected $_storeMessage =>
      bool(false)
      protected $_storeMessageUCS2 =>
      bool(false)
      protected $_dataCodingAndMessageClass =>
      bool(false)
      protected $_messageIndication =>
      bool(false)
      protected $_messageIndicationType =>
      bool(false)
    }
    protected $_udl =>
    NULL
    protected $_ud =>
          ...

  }
}
string(151) "If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS ewwe rwe rwer wer werwe rwe rwe rwer will automatica"
0011000B911311113254F60000AA97493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29A87CBF9741F27B1924BF97E5A07B590EBA97E5F732487E2F83E4F732487E2FCB41F7349B0D0AD7E9EF76989E1E8701
```

**Comment by 3sco** [comment]
Im very sorry
this Msg is
"If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS  ewwe rwe rwer wer werwe rwe rwe rwer will automatically perform this segmentation to create hahah dhsd sdfklsdf sdfklsdfsd sdfksdf"

0071000B911311113254F60000AAA00608045BB70201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD290854BEDFCB20F9BD0C92DFCB72D0BD2C07DDCBF27B1924BF9741F27B1924BF97E5A07B9ACD0685EBF4773B4C4F8FC36C 
chars 152(98) but it's set 160 (A0)

0071000B911311113254F60000AA540608045BB70202EC3C085E969BDFF236888E4ECF41F3F2B95D76D3C3F4F4DB0DA2BF416379394C2F83D06174180D22A3E764D09C6C5EB3E76433684E36AFD973B2794E06CDC9E6F59C6C06

chars 76 (4c) but it's set  84 (54)

**Comment by jackkum** [comment]
Header length including in user data length.
I can't find docs on english, have only russian.
Look in here: http://mobiletidings.com/2009/02/18/combining-sms-messages/

**Comment by 3sco** [comment]
OK but when i send it by asterisk I get error "data length exceeds"

**Comment by 3sco** [comment]
I know where is problem :)
0051000B918466508434F00000AAA006080497A70201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E965

Message is to long for one char
is "If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to create" 
should be 

"If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to crea"

in PDU
is 0051000B918466508434F00000AAA006080497A70201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E965
should be 
0051000B918466508434F00000AAA006080497A70201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E9

**Comment by 3sco** [comment]
IF is 7bit msg and there is more then one  sms Header should be set 7 in other case's should be set header 8

**Comment by jackkum** [comment]
Oh, crazy day )))
Tomorrow I will do this.

**Comment by 3sco** [comment]
ok great

**Comment by jackkum** [comment]
I make possible set maximum limit for segment.
```php
Helper::setLimit(159, 'compress');
```
I check it in gsm modem (7bit and unicode), sms successfully delivered.

I don't understand about 7 or 8 header.
Header can be 6 or 7 byte.
06 08 04 9931 03 01
06 - Length of User Data Header (UDL), in this case 06.
08 - Information Element Identifier, equal to 08 (Concatenated short messages, 16-bit reference number)
04 - Length of the header, excluding the first two fields; equal to 04
9931 - 0000-FFFF, CSMS reference number, must be same for all the SMS parts in the CSMS
03 - 00-FF, total number of parts. The value shall remain constant for every short message which makes up the concatenated short message. If the value is zero then the receiving entity shall ignore the whole information element
01 - 00-FF, this part's number in the sequence. The value shall start at 1 and increment for every short message which makes up the concatenated short message. If the value is zero or greater than the value in Field 5 then the receiving entity shall ignore the whole information element
From here: https://en.wikipedia.org/wiki/Concatenated_SMS

**Comment by 3sco** [comment]
Try to send 
"If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to create header equipment"

Message is split to:

 0 =>  'If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to create' (length=153)
  1 => ' header equipment' (length=17)

First message should 152 length and second should be 18 length
Result in PDU is :
 0 => 0051000B911398795634F20000AAA006080461BF0201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E965

1 => 0051000B911398795634F20000AA1806080461BF02022074394C2ECB41E5783D0D6F97DD74

check on this page : http://smspdu.benjaminerhart.com/
first part of message response with "PDU longer than expected!"

**Comment by jackkum** [comment]
![2015-06-22 15 17 20](https://cloud.githubusercontent.com/assets/2418167/8277202/4ef9c800-18ea-11e5-8473-10fce3387f3b.png)

**Comment by 3sco** [comment]
Yes do you see? That message is to long? I try to send message on modem but I get errors cause message is to long

**Comment by jackkum** [comment]
User Data Length	160 characters, 140 bytes

**Comment by jackkum** [comment]
PDU longer than expected!

**Comment by 3sco** [comment]
yes as i wroted 
if you cut message

0051000B911398795634F20000AAA006080461BF0201493328FFAECBCBA0795DDC4ED3E969F719442FE3E9207B3A0CA2A3CB20E7FB3E6D4E41F7B2189476D3CB7273785C06A1DE7210392D2F8FE92024950A0555A54CD0BC2E6EA7E7F3F4DB9D6281E8E8B21BE47CDFA7CD29E89E66B341E13AFDDD0ED3D3E3309B9D07C1CB72F35BDE06D1D1E939685E3EB7CB6E7A989E7EBB41F437682C2F87E9
is ok

User Data Length 160 characters, 140 bytes

**Comment by jackkum** [comment]
It's a strange, maybe it's a bug? 
real length of message above is 152 + 7 = 159
i can make 159 length for 7bit message as default and it will work.

**Comment by 3sco** [comment]
If message is longer then one sms should be one bit left (i dont know why) but looks like it should be.

**Comment by 3sco** [comment]
You mean bug on page "http://smspdu.benjaminerhart.com/"? I dont think so cause when I try to send message by modem I have error message length exceeds

**Comment by jackkum** [comment]
this PDU: https://github.com/jackkum/PHPPDU/issues/27#issuecomment-114028032

from site: 'If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to crea'

from this package: 'If youre submitting text via the NowSMS web interface (or direct HTTP URL submission), then NowSMS will automatically perform this segmentation to creat'

**Comment by 3sco** [comment]
Fatal error: Call to undefined method jackkum\PHPPDU\Submit::getStart() in vendor/jackkum/phppdu/PDU/Data/Part.php on line 187

**Comment by jackkum** [comment]
Can you show code, i can't repeat this?

**Comment by 3sco** [comment]
Sorry my fault is working

**Comment by 3sco** [comment]
test it . Works great
