### ISSUE TITLE
Multipart SMS

### ISSUE THREAD

**Issue by axwell** [jackkum/PHPPDU#33]
Hello jackkum great work with the library.
I have one question about multipart SMS. I'm trying to send one but it seems that UDH is not added and message gets some weird chars at the begining.
Can you help me ? Thanks.

$newpdu = new Submit();
$newpdu->setAddress('+400720123456');
$newpdu->setData('Ana are mere si pere.') * Repeat message until gets long;
$newpdu->setVp(3600);
$newpdu->initType(['srr' => 1]);

Message will start like this when decoded.
ùΔΔ03K¡@Ana are mere si pere

**Comment by axwell** [comment]
I found out if i remove $newpdu->initType(['srr' => 1]); everything it's ok, is there another way to set sms delivery ?

**Comment by jackkum** [comment]
Hello @axwell try code below:
```php
$newpdu = new Submit();
$newpdu->setAddress('+400720123456');
$newpdu->setData('Ana are mere si pere.') * Repeat message until gets long;
$newpdu->setVp(3600);
// get type of data (\PDU\Type\Submit) and set status report request
$newpdu->getType()->setSrr(1);
```

**Comment by axwell** [comment]
Works perfectly ! Thanks.
